# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60d7a73a673d9571bf1f68b622386119443bd08961e20702b5c1a1f9e447f5b987fbe64c646c2613d431f17aa33956027cdd4b764ba38758e301c4dd536d4941

test:
  secret_key_base: 9c72afbc09e3482c16840665ae460f526682d2d107c75464449a6f628eb0d034f6c25512e485a9c38989e156f440688d87629f1f7a949a6392c69ddfa7c3a390

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
